name: Playwright Tests With Search02
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # 每30分钟
    - cron: '*/26 * * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
    - name: Run Playwright tests
      run: export IS_GITHUB_ACTION=true && export TEST_NO_PROXY=true && pnpm run test:google
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
